### ISSUE TITLE
Can not work with react, cause runtime error: $RefreshSig$ is not defined

### ISSUE THREAD

**Issue by shunia** [windsonR/vite-plugin-virtual-html#12]
I was looking for the 'rename html file' post build functionality.
it works in dev mode, output renamed html file correctly, but after open the dev url, console shows runtime error: $RefreshSig$ is not defined.
Without this plugin, html served correctly (with unwanted file name though), no runtime error.
Config:
```typescript
import React from '@vitejs/plugin-react'
import VirtualHtml from 'vite-plugin-virtual-html'

return defineConfig({
  ...
  plugins: [
    react(),
    virtualHtml({
      pages: { index: `/index.${mode}.html` }
    })
  ],
  ...
})
```

**Comment by WindsonFF** [comment]
can u provide a demo for this?

**Comment by windsonR** [comment]
0.2.1 now can work with react.
