### ISSUE TITLE
vite.config.ts build.rollupOptions gets overwritten

### ISSUE THREAD

**Issue by djpogo** [windsonR/vite-plugin-virtual-html#15]
Hey @windsonR,

thx for this plugin.

I try to remove the hashes from the generated files via the [rollupOptions](https://vitejs.dev/config/#build-rollupoptions) and noticed that your plugin overwrites the `config.rollupOptions` at this place: https://github.com/windsonR/vite-plugin-virtual-html/blob/main/src/plugin.ts#L68

My `vite.config.ts` looks like this:

``` js
export default defineConfig({
	build: {
		rollupOptions: {
			output: {
				entryFileNames: '[name].js',
				chunkFileNames: '[name].js',
				assetFileNames: '[name].[ext]',
			}
		}
	},
        ...
	plugins: [
        	virtualHtml({
			pages: { index: 'index.hbs', page2: 'page2.hbs' },
		}),
	]
});
```

**Comment by windsonR** [comment]
thx for you PR.
it's already merged.
