### ISSUE TITLE
yarn build 出错

### ISSUE THREAD

**Issue by shileima** [windsonR/vite-plugin-virtual-html#18]
<img width="846" alt="image" src="https://user-images.githubusercontent.com/3283706/154932941-9d2a48e9-6d89-4664-ad3a-ac0103448b71.png">

使用的模板是：
<img width="860" alt="image" src="https://user-images.githubusercontent.com/3283706/154933031-d95eb385-8e76-4407-a795-85dd1c96d286.png">

配置的模板：
<img width="688" alt="image" src="https://user-images.githubusercontent.com/3283706/154933153-32e471ac-ae9b-4725-ac4a-bdb4debb3444.png">

请问这是什么错误？

**Comment by windsonR** [comment]
使用src的时候请将完整的script标签作为模板的数据写进去。
可以看看[template.html](https://github.com/windsonR/vite-plugin-virtual-html/blob/b61e67946c35b32432da991df4a5e61b5c2949eb/demo/template.html#L6) 以及[vite.config.ts](https://github.com/windsonR/vite-plugin-virtual-html/blob/b61e67946c35b32432da991df4a5e61b5c2949eb/vite.config.ts#L36)
