### ISSUE TITLE
script标签位置问题

### ISSUE THREAD

**Issue by swhoro** [windsonR/vite-plugin-virtual-html#20]
vite配置：
```js
const pages = {
  index: {
    template: '/public/index.html',
    data: {
      entry: '/src/index.tsx'
    },
    render(m, d) {
      return ejs.render(m, d);
    }
  },
  index2: {
    template: '/public/index2.html',
    data: {
      entry: '/src/index2.tsx'
    },
    render(m, d) {
      return ejs.render(m, d);
    }
  }
};

return {
      css: {
        modules: {
          scopeBehaviour: 'local',
          localsConvention: 'camelCase'
        }
      },
      build: {
        outDir: './dist',
        // 静态资源输出目录
        assetsDir: './assets',
        // 静态资源开发目录
        publicDir: './publi/assets'
      },
      plugins: [
        viteExternalsPlugin({
          react: 'React',
          'react-dom/client': 'ReactDOM'
        }),
        virtualHtml({
          pages: pages
        })
      ]
    };
````

html模板：
![image](https://user-images.githubusercontent.com/34229589/172431740-ade9c898-41ca-4d6d-b87d-0f86490b3ec3.png)

生成的html文件：
![image](https://user-images.githubusercontent.com/34229589/172431856-c92b4217-6f37-4924-b6ab-00d90982c0af.png)

script标签从body底部变为了head中，请问有办法解决吗
另外问下vite貌似自动给我生成了一个modulereload-polyfill 的js文件，请问下这个是干嘛用的

**Comment by swhoro** [comment]
谢谢，但是又有新的问题了
html文件现在是这样的：
![image](https://user-images.githubusercontent.com/34229589/172571781-2bec960a-bc05-43fe-aa7a-0186309e1107.png)
config没变，只是把cdn内容改了一下：
```js
  const cdn = [
    '<script src="https://cdn.bootcdn.net/ajax/libs/react/18.1.0/umd/react.production.min.js"/>',
    '<script src="https://cdn.bootcdn.net/ajax/libs/react-dom/18.1.0/umd/react-dom.production.min.js"/>'
  ];
```

现在build没问题，但是启动开发服务器有问题
不加路径访问indexPage没问题，就跟访问index.html一样
但是访问 /index.html 或者 /index2.html 会变成模板内容：
![image](https://user-images.githubusercontent.com/34229589/172572356-958a523e-1628-4f18-bbad-98db34120e75.png)

**Comment by windsonR** [comment]
提供一下你的代码呢.

**Comment by swhoro** [comment]
> 提供一下你的代码呢.

https://github.com/swhoro/react-learning

**Comment by swhoro** [comment]
> 测试没问题.

我重新克隆了一遍还是有问题...
用npm和pnpm都是的...
这咋办啊

**Comment by windsonR** [comment]
因为你把你的模板html文件放到了public目录,但是你又没有重新设置一个新的'public'目录,然后在vite编译之后,会将'public'目录下的文件复制到'dist'下,然后,就会导致这个错误.建议把html文件放其他目录下,或者修改'publicDir'配置为其他目录.
但是我好奇的是为什么build的时候html文件没有被覆盖.

**Comment by swhoro** [comment]
> 因为你把你的模板html文件放到了public目录,但是你又没有重新设置一个新的'public'目录,然后在vite编译之后,会将'public'目录下的文件复制到'dist'下,然后,就会导致这个错误.建议把html文件放其他目录下,或者修改'publicDir'配置为其他目录.
> 但是我好奇的是为什么build的时候html文件没有被覆盖.

想起来了，好像build的时候我设置了静态资源目录在public/assets里
server的时候不知道可不可以设置静态资源目录

**Comment by swhoro** [comment]
谢谢，问题成功解决了
