### ISSUE TITLE
能否内置模板处理函数，比如内置ejs引擎

### ISSUE THREAD

**Issue by emosheeep** [windsonR/vite-plugin-virtual-html#22]

**Comment by windsonR** [comment]
有提供模板调用方法。具体用什么模板引擎是使用者自己的事情。

**Comment by emosheeep** [comment]
但是提供一个通用解决方案也会更加便利呀hh

**Comment by windsonR** [comment]
欢迎PR

**Comment by windsonR** [comment]
0.3.2对于默认的render添加了ejs调用.

**Comment by emosheeep** [comment]
get了，我那阵儿急着用自己写了一个一共150行代码，有参考你这边的实现思路~，https://github.com/emosheeep/vite-plugin-virtual-mpa
