### ISSUE TITLE
Module 'ejs' is not found! Did you install it?

### ISSUE THREAD

**Issue by jackson-yyy** [windsonR/vite-plugin-virtual-html#24]
https://github.com/windsonR/vite-plugin-virtual-html/blob/c16067f6197c2c5ac434483d75634e0666492e22/package.json#L38

这个是否可以放到dependencies里自动安装，或者有其他更好的文案方式，现在项目里没有用到ejs，但每次打包都会提示未安装，有点奇怪

**Comment by windsonR** [comment]
这个目前只会提示一次.下个版本会想办法把他丢vite的debug信息里边去显示.

**Comment by windsonR** [comment]
0.4.1引入了`debug`模块,这些信息应该都不会显示在正常的启动中了.
