### ISSUE TITLE
运行vite build 会导致root目录被整个删除

### ISSUE THREAD

**Issue by mileswxn** [windsonR/vite-plugin-virtual-html#29]
![Screenshot 2023-07-05 at 3 54 35 PM](https://github.com/windsonR/vite-plugin-virtual-html/assets/4205507/cdf8b361-677d-414b-bc5a-0019f24f31ce)

项目的结构如上图所示

vite.config.js中的设置如下：

```
const virtualHtml = require('vite-plugin-virtual-html').default

export default {
  root: 'frontend',
  build: {
    outDir: '../dist',
  },
  plugins: [
    virtualHtml({
      pages: {
        index: {
          entry: 'main.js',
          template: '/template/template.html',
          data: {
            title: 'Test'
          }
        },
      },
      indexPage: 'index',
    }),
  ],
}
```

运行 `vite build`之后，frontend目录就会被删除。运行 `vite`并不会删除目录。

如果在frontend目录下放一个 index.html，也可以避免文件夹被删除。

**Comment by windsonR** [comment]
嗯,在检查html文件的父目录的时候没有考虑到`config.root`配置了的情况

**Comment by mileswxn** [comment]
刚试了试1.1.11版本，文件夹不会被删除，但是build出来的index.html并不是用template render出来的，猜测还是和root的配置有关。

**Comment by windsonR** [comment]
是这样子的,`entry`和`template`不能同时使用.
如果在有`entry`的时候,会自动生成html文件.

看你的配置,应该是想通过一个template文件自动生成多个不同入口的html文件,这个可以参考`vite.config.ts`中的[demo4](https://github.com/windsonR/vite-plugin-virtual-html/blob/ef34dfd665d706ee6a05068f38d1f4c62598907b/vite.config.ts#L35)
配置进行处理.

**Comment by mileswxn** [comment]
您好，我根据demo4的配置去掉entry之后，的确template就生效了，但是又遇到了新的问题，`vite build`出来的index.html文件并没有经过ejs的render步骤，而运行`vite`出来的index.html是正确的。



```
<!-- 这是vite出来的html, ejs的tag并没有被处理 -->
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta name="description" content="Test page">
    <title><%= title %></title>
  <script type="module" crossorigin src="/assets/index-5aa38de4.js"></script>
</head>
<body>
<div id="app"></div>

</body>
</html>
```

```
<!-- 这是vite出来的html -->
<!DOCTYPE html>
<html>
<head>
    <script type="module" src="/@vite/client"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta name="description" content="Test page">
    <title>Test</title>
</head>
<body>
<div id="app"></div>
<script src="/main.js" type="module"></script>
</body>
</html>
```

**Comment by windsonR** [comment]
能提供一下可重现的代码么？

**Comment by mileswxn** [comment]
我把重现的代码推到这里

https://github.com/mileswxn/vite-test-project

**Comment by windsonR** [comment]
找到原因了,在build的时候,config没有传进去...

**Comment by mileswxn** [comment]
非常感谢，我这里一切正常了。
