### ISSUE TITLE
[vite] Internal server error: URI malformed

### ISSUE THREAD

**Issue by tqh7678** [windsonR/vite-plugin-virtual-html#30]
请问rewrites有测过吗？
![image](https://github.com/windsonR/vite-plugin-virtual-html/assets/43992590/c260bd70-63de-4600-9b12-51a4dc99ee33)
配什么都会报错，放个空数组也会

**Comment by windsonR** [comment]
肯定是测试过的嘛,是遇到什么问题了么?能提供详细的堆栈信息么?
