### ISSUE TITLE
Routing issues

### ISSUE THREAD

**Issue by bmw20075112** [windsonR/vite-plugin-virtual-html#35]
Please check [Example repository](https://stackblitz.com/edit/vitejs-vite-so6992?file=vite.config.ts).

I have set three pages(index, cat, dog) in vite.config.ts.

In page Index, it works good.

But if I go to /cat or /dog, I will get response  'Cannot GET /[name]'.

If I set `indexPage` to 'cat', page cat will show, but other two pages still crash.

Could anyone help me check what can I do to fix this problem?

<img width="422" alt="截圖 2023-12-01 下午12 46 50" src="https://github.com/windsonR/vite-plugin-virtual-html/assets/54742414/18b8c84b-f88b-40fe-97d9-06be910cd85f">

**Comment by windsonR** [comment]
In the pages config, for example: 
<img width="486" alt="image" src="https://github.com/windsonR/vite-plugin-virtual-html/assets/11462711/a2dad9ca-e48a-423c-a2ad-0228e4ffd4e7">


`cat` means `http://localhost:5173/cat.html` to get HTML `/src/cat.html`. IT STILL NEED YOU USE `cat.html` to access

`dog/` means `http://localhost:5173/dog/index.html`.

If you want to access `http://localhost:5173/cat` to get HTML `src/cat.html`, maybe you can use `urlTransformer` to customize, just like this
<img width="492" alt="image" src="https://github.com/windsonR/vite-plugin-virtual-html/assets/11462711/1e28a9dc-7258-49b3-a917-d5935bda5062">

**Comment by windsonR** [comment]
It has been a long time since there was a response, so this ISSUE is now closed.
