### ISSUE TITLE
plugin auto-remove folders on root when have name same as page keys.

### ISSUE THREAD

**Issue by FarhanMS123** [windsonR/vite-plugin-virtual-html#38]
Here are my working repository: \
https://github.com/FarhanMS123/vite-mpa-framework-files-router/tree/experiment/test-plugin-mpa

Somehow, I have this structure

```bash
src/
\_ clean.html
\_ vite-env.ts
test/
\_ assets/
|  \_ react.svg
|  \_ vite.svg
\_index.css
\_ main.tsx
vite.config.ts
... rest of standard vite files ...
```

This configuration below fullfil this condition:
- It would get template from `/src`
- The pages is all on root (not inside `/src`), e.g `/test/*.tsx`
- Public is also on root which all must be copied to `/dest` except defined on `build.rollupOptions.external`

```ts
// vite.config.ts
export default defineConfig({
  plugins: [
    virtualHtml({
      pages: {
        "test/hello.tsx": {
          template: "/src/clean.html",
          data: {
            script_src: "/test/main.tsx"
          },
        },
      },
    }),
    splitVendorChunkPlugin(),
    react(),
  ],

  build: {
    rollupOptions: {
      external: /^(.git|.*\.local|dist|node_modules)$/ig,
    },
  },

  root: process.cwd(),
  publicDir: ".",
  base: "/",
})
```

- [File `src/clean.html`](https://github.com/FarhanMS123/vite-mpa-framework-files-router/blob/experiment/test-plugin-mpa/src/clean.html)

---

## What happend?

This configuration compiling by:
1. make `/test` folder and subdir as defined in `pages[keys]` and recreate file with template
2. Copy public files (everything inside root) to `/dist` with no respect to `build.rollupOptions.external`
3. Remove `/test` folder everything inside it

## Other issue founds
- I assume when i make a file as `test/hello.tsx.html`, the plugin would override the file. But no, it unexpectedly become the resistent of the plugin, which in simply, the `/test` is not removed. And unexpectedly the html really compiled successfully. (Still public folder is copied without respect to `build.rollupOptions.external`)
- When `pages[key].template` not started by backslash, it would add `dot` to the path. E.g. `src/clean.html` becomes `path/from/root/.src/clean.html`

**Comment by windsonR** [comment]
1. In `dev` mode , plugin will intercept any `html` request when it ends with `*.html` or `/`. In your repo , you add a `.tsx` suffix, in my opinion, it will be transformed by `react` plugin finally, so you should remove the `.tsx` affix.
2. In `build` mode, plugin will generate a `html`file in `project root`, and when build end(`closeBundle`), It will delete all file that plugin generated.
3. In you repo, you use a `test` as the `html`'s middle path, so when build, it will generate a `hello.tsx.html` in your `test` directory. And when build end , it will delete `test`directory.

So, i suggest you change your config like this: 

``` javascript
{
pages: {
- "test/hello.tsx": {
+ "test1/hello": {
          template: "/src/clean.html",
          data: {
            script_src: "/test/main.tsx"
          },
        },
}
}
```
Or, if you want to use `*.tsx` as the access URL in browser, maybe you want to try `urlTransformer` to customize.

**Comment by FarhanMS123** [comment]
So... It is intended? Alright... I will give it a chance. Thankyou.
