### ISSUE TITLE
vite build fails with new templates

### ISSUE THREAD

**Issue by zoranpopovic** [windsonR/vite-plugin-virtual-html#8]
While vite dev works with ejs templates, vite build produces an error:
```
[vite-plugin-virtual-html] Cannot read property 'data' of undefined
file: C:/Users/zoran/src/enlearn/math/ViteTemplate.html
error during build:
TypeError: Cannot read property 'data' of undefined
    at Object.transform (C:\Users\zoran\src\enlearn\math\node_modules\vite-plugin-virtual-html\src\index.js:120:44)
    at C:\Users\zoran\src\enlearn\math\node_modules\vite\node_modules\rollup\dist\shared\rollup.js:22620:25
```

**Comment by windsonR** [comment]
> ok, there are 2 issues here:
> 
> First, as @windsonR said, key name needs to be the same as the template name. that seems very restrictive, especially when the same template is used to create multiple pages (for example, same html template, but a different main.js script that is changed via template to generate many separate vue pages). I'm not sure why this restriction exists. the template and the actual url should be independent. template is just used to get the source, but everything else within the plugin should use the key, as that's the real name of the page. Also, vite dev has no problem with template being a different name than key, but vite build does have an issue.
> 
> Second, even when the template name and the key are the same, there is an issue that happens when template is in the root directory. For example, if you modify the vite.config.js to have this pages object:
> 
> ```
>       pages: {
>         demo1: {
>           html: '/demo/demo1/demo1.html',
>           data: {
>             users: ['a','b','c']
>           }
>         },
>         demo2: '/demo/demo2/demo2.html',
>         // demo2: {
>         //   html: '/demo/demo2/demo2.html'
>         // },
>         demo3: '/demo3.html',
>         data: {
>           users: ['a','b','c']
>         }
>       },
> ```
> 
> and just copy /demo/demo1/demo1.html to the root directory as ./demo3.html, so that demo3 would find it, `yarn test:build` fails, and vite build in general.
> 
> ```
> error during build:
> Error: ENOENT: no such file or directory, rmdir 'C:\Users\zoran.CSENETID\src\enlearn\vite-plugin-virtual-html\dist\demo3.html'
> error Command failed with exit code 1.
> ```

1. i have refactored plugin, the pages key and the html now can different.
2. new version have reworked the plugin work in build process.this will not happen again(maybe)
